// Auto-generated by OpenLane
module ascon_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst,
  input sclk,
  input cs_n,
  input mosi,
  output clk_PU,
  output clk_PD,
  output rst_PU,
  output rst_PD,
  output cs_n_PU,
  output cs_n_PD,
  output sclk_PU,
  output sclk_PD,
  output mosi_PU,
  output mosi_PD,
  output miso_OUT,
  input miso_IN,
  output miso_IE,
  output miso_OE,
  output miso_PU,
  output miso_PD,
  output miso_CS,
  output miso_SL,
  output miso_PDRV1,
  output miso_PDRV0
);
endmodule
